apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx 
spec:
  type: NodePort  #Change this to LoadBalancer later
  ports:
  - port: 80
    targetPort: web-port
   
  selector:
    app: nginx
